GET http://localhost:4000
Accept: application/json

###
GET http://localhost:4000/blocks

###
POST http://localhost:4000/blocks
Content-Type: application/json

{
  "message": "my block data"
}

###
GET http://localhost:4000/balance/7f7e3e4954542ebf5fd1436054c3e3a790d20398a4902a630e25819f49c7b0049cb4d10e26730f84286b90fd24f699e07dcf5ca50f941351f9ea555801a58e35

###
GET http://localhost:4000/balance/someone?total=true

###
POST http://localhost:4000/transactions
Content-Type: application/json

{
  "to": "someone",
  "amount":40
}

###
GET http://localhost:4000/mempool

###
GET http://localhost:4000/wallet